openapi: 3.0.0
info:
  title: 다시 스탠드 API
  description: |
    다양한 정치적 관점에서 뉴스를 제공하는 서비스의 API입니다.
    동일 이슈에 대한 다양한 출처의 뉴스를 비교할 수 있게 해주는 플랫폼입니다.
  version: 1.0.0
  contact:
    name: 패션개발자들
    email: api@dasi-stand.com

servers:
  - url: https://492ipc4742.execute-api.ap-northeast-2.amazonaws.com
    description: 배성민 사비로 운영되는 테스트 서버

security:
  - bearerAuth: []

# CORS 정책 정보
x-cors:
  enabled: true
  origins:
    - "https://www.dasi-stand.com"
    - "https://app.dasi-stand.com"
    - "http://localhost:3000"
  methods:
    - GET
  headers:
    - Content-Type
    - Accept
  maxAge: 86400  # 24시간

tags:
  - name: 이슈
    description: 주요 뉴스 이슈 관련 API
  - name: 사용자
    description: 사용자 정치성향 관련 API


paths:
  /issues:
    get:
      summary: 주요 이슈 목록 조회
      description: 현재 주요 뉴스 이슈 목록을 반환합니다.
      tags:
        - 이슈
      parameters:
        - name: limit
          in: query
          description: 반환할 이슈 수 (기본값 10)
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 50
        - name: lastIssueId
          in: query
          description: 마지막으로 읽은 이슈의 아이디 (페이징용)
          schema:
            type: string
      responses:
        '200':
          description: 성공적으로 이슈 목록을 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssuesListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /issues/{issueId}:
    get:
      summary: 특정 이슈 상세 정보 조회
      description: 특정 이슈의 상세 정보와 다양한 관점의 뉴스 기사를 반환합니다.
      tags:
        - 이슈
      parameters:
        - name: issueId
          in: path
          description: 이슈 ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 성공적으로 이슈 상세 정보를 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueDetailFullResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /user/political-preference:
    post:
      summary: 사용자 정치성향 설정/변경
      description: |
        사용자의 정치성향을 설정하거나 변경합니다.
        JWT 토큰으로 사용자를 식별하며, 조작 방지를 위해 서버에서 검증합니다.
      tags:
        - 사용자
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PoliticalPreferenceRequest'
      responses:
        '200':
          description: 정치성향 설정/변경 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoliticalPreferenceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:

    PoliticalPreferenceRequest:
      type: object
      description: 정치성향 설정 요청
      properties:
        perspective:
          type: string
          enum: ["left", "center_left", "center", "center_right", "right"]
          description: 사용자의 정치성향
          example: "center"
      required:
        - perspective
      additionalProperties: false

    PoliticalPreferenceResponse:
      type: object
      description: 정치성향 설정/변경 응답
      properties:
        message:
          type: string
          description: 성공 메시지
          example: "정치성향이 성공적으로 설정/변경되었습니다"
        perspective:
          type: string
          enum: ["left", "center_left", "center", "center_right", "right"]
          description: 설정된 정치성향
          example: "center"
        userEmail:
          type: string
          format: email
          description: 사용자 이메일 (JWT에서 추출)
          example: "user@example.com"
        timestamp:
          type: string
          format: date-time
          description: 설정/변경 시간
          example: "2025-06-06T12:00:00Z"
      required:
        - message
        - perspective
        - userEmail
        - timestamp
      additionalProperties: false

    CoverageSpectrum:
      type: object
      description: 정치적 스펙트럼 분포
      properties:
        left:
          type: integer
          minimum: 0
          description: 좌성향(left, center_left) 기사 개수
          example: 5
        center_left:
          type: integer
          minimum: 0
          description: 중도 좌성향 기사 개수
          example: 2
        center:
          type: integer
          minimum: 0
          description: 중도 성향 기사 개수
          example: 3
        center_right:
          type: integer
          minimum: 0
          description: 중도 우성향 기사 개수
          example: 3
        right:
          type: integer
          minimum: 0
          description: 우성향(center_right, right) 기사 개수
          example: 4
        total:
          type: integer
          minimum: 0
          description: 전체 기사 개수
          example: 12
      required:
        - left
        - center
        - right
        - total
      additionalProperties: false

    CategoryInfo:
      type: object
      description: 미디어 소스의 카테고리 정보
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
          description: 카테고리 이름
          example: "정치"
        url:
          type: string
          format: uri
          maxLength: 2000
          description: 카테고리 URL
          example: "https://example-news.com/politics"
      required:
        - name
        - url
      additionalProperties: false

    # 응답 모델들
    IssueResponse:
      type: object
      description: 이슈 기본 응답 모델 (목록용)
      properties:
        _id:
          type: string
          description: 이슈 ID
          example: "507f1f77bcf86cd799439011"
        title:
          type: string
          description: 이슈 제목
          example: "미국과 중국 간 무역 분쟁 심화"
        category:
          type: string
          enum: ["politics", "economy", "society", "culture", "international", "environment"]
          description: 이슈 카테고리
          example: "international"
        summary:
          type: string
          description: 이슈 요약
          example: "미국과 중국 간 무역 관계가 악화되며 글로벌 경제에 영향을 미치고 있습니다."
        imageUrl:
          type: string
          format: uri
          description: 이슈 관련 이미지 URL
          example: "https://example-cdn.com/images/trade-war.jpg"
          nullable: true
        keywords:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 200
          description: 이슈 관련 키워드
          example: ["미국", "중국", "무역분쟁"]
        createdAt:
          type: string
          format: date-time
          description: 생성 시간
          example: "2025-05-20T09:30:00Z"
        view:
          type: integer
          minimum: 0
          description: 조회 수
          example: 1500
        coverageSpectrum:
          $ref: '#/components/schemas/CoverageSpectrum'
        updatedAt:
          type: string
          format: date-time
          description: 업데이트 시간
          example: "2025-05-21T08:15:00Z"
          nullable: true
      required:
        - _id
        - title
        - category
        - summary
        - createdAt
        - view
        - coverageSpectrum
        - keywords
      additionalProperties: false

    IssueDetailResponse:
      allOf:
        - $ref: '#/components/schemas/IssueResponse'
        - type: object
          description: 이슈 상세 응답 모델
          properties:
            leftSummary:
              type: string
              description: 좌성향 관점 요약
              example: "미국의 중국에 대한 새로운 관세 부과는 보호무역주의적 조치입니다."
            centerSummary:
              type: string
              description: 중도 관점 요약
              example: "미국과 중국 간 무역 분쟁이 더욱 심화되고 있습니다."
            rightSummary:
              type: string
              description: 우성향 관점 요약
              example: "미국의 중국에 대한 관세 부과는 필요한 조치입니다."
            biasComparison:
              type: string
              description: 편향 비교 요약
              example: "좌성향은 보호무역주의를 비판하며, 우성향은 국가 안보를 강조합니다."
            leftKeywords:
              type: array
              items:
                type: string
                minLength: 1
                maxLength: 200
              description: 좌성향 키워드
              example: ["보호무역주의", "다자간협력"]
              nullable: true
            centerKeywords:
              type: array
              items:
                type: string
                minLength: 1
                maxLength: 200
              description: 중도 키워드
              example: ["글로벌경제", "불확실성"]
              nullable: true
            rightKeywords:
              type: array
              items:
                type: string
                minLength: 1
                maxLength: 200
              description: 우성향 키워드
              example: ["국가안보", "산업보호"]
              nullable: true
          required:
            - leftSummary
            - centerSummary
            - rightSummary
            - biasComparison
          additionalProperties: false

    SourceInfo:
      type: object
      description: 기사 응답에 포함될 소스 정보
      properties:
        _id:
          type: string
          description: 미디어 소스 ID
          example: "507f1f77bcf86cd799439013"
        name:
          type: string
          description: 미디어 소스 이름
          example: "대한일보"
        perspective:
          type: string
          enum: ["left", "center_left", "center", "center_right", "right"]
          description: 정치적 성향
          example: "center"
      required:
        - _id
        - name
        - perspective
      additionalProperties: false

    ArticleResponse:
      type: object
      description: 기사 응답 모델
      properties:
        _id:
          type: string
          description: 기사 ID
          example: "507f1f77bcf86cd799439012"
        title:
          type: string
          description: 기사 제목
          example: "미국의 새로운 관세 정책, 글로벌 시장에 미치는 영향"
        preview:
          type: string
          description: 기사 프리뷰
          example: "미국이 중국산 제품에 새로운 관세를 부과하기로 결정했습니다..."
        url:
          type: string
          format: uri
          description: 기사 URL
          example: "https://example-news.com/articles/123"
        reporter:
          type: string
          description: 기자 이름
          example: "김기자"
          nullable: true
        publishedAt:
          type: string
          format: date-time
          description: 발행 시간
          example: "2025-05-20T14:30:00Z"
        issueId:
          type: string
          description: 관련 이슈 ID
          example: "507f1f77bcf86cd799439011"
        category:
          type: string
          enum: ["politics", "economy", "society", "culture", "international", "environment"]
          description: 기사 카테고리
          example: "international"
        imageUrl:
          type: string
          format: uri
          description: 기사 이미지 URL
          example: "https://example-news.com/images/article123.jpg"
          nullable: true
        source:
          $ref: '#/components/schemas/SourceInfo'
      required:
        - _id
        - title
        - preview
        - url
        - publishedAt
        - issueId
        - category
        - source
      additionalProperties: false

    HotIssueResponse:
      type: object
      description: 핫이슈 응답 모델 (이미지 URL 필수)
      properties:
        _id:
          type: string
          description: 이슈 ID
          example: "507f1f77bcf86cd799439011"
        title:
          type: string
          description: 이슈 제목
          example: "미국과 중국 간 무역 분쟁 심화"
        category:
          type: string
          enum: ["politics", "economy", "society", "culture", "international", "environment"]
          description: 이슈 카테고리
          example: "international"
        summary:
          type: string
          description: 이슈 요약
          example: "미국과 중국 간 무역 관계가 악화되며 글로벌 경제에 영향을 미치고 있습니다."
        imageUrl:
          type: string
          format: uri
          description: 핫이슈 관련 이미지 URL (필수)
          example: "https://example-cdn.com/images/trade-war.jpg"
        keywords:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 200
          description: 이슈 관련 키워드
          example: ["미국", "중국", "무역분쟁"]
        createdAt:
          type: string
          format: date-time
          description: 생성 시간
          example: "2025-05-20T09:30:00Z"
        view:
          type: integer
          minimum: 0
          description: 조회 수
          example: 1500
        coverageSpectrum:
          $ref: '#/components/schemas/CoverageSpectrum'
        updatedAt:
          type: string
          format: date-time
          description: 업데이트 시간
          example: "2025-05-21T08:15:00Z"
          nullable: true
      required:
        - _id
        - title
        - category
        - summary
        - imageUrl
        - createdAt
        - view
        - coverageSpectrum
        - keywords
      additionalProperties: false

    HotIssuesResponse:
      type: object
      description: 핫이슈 목록 응답 모델
      properties:
        issues:
          type: array
          items:
            $ref: '#/components/schemas/HotIssueResponse'
          description: 핫이슈 목록
        totalCount:
          type: integer
          minimum: 0
          description: 전체 핫이슈 개수
          example: 5
      required:
        - issues
        - totalCount
      additionalProperties: false

    IssuesListResponse:
      type: object
      description: 이슈 목록 응답 모델
      properties:
        issues:
          type: array
          items:
            $ref: '#/components/schemas/IssueResponse'
          description: 이슈 목록
        hasMore:
          type: boolean
          description: 더 많은 데이터가 있는지 여부
          example: true
        lastIssueId:
          type: string
          description: 마지막 이슈 ID (페이징용)
          example: "507f1f77bcf86cd799439011"
      required:
        - issues
        - hasMore
        - lastIssueId
      additionalProperties: false

    IssueDetailFullResponse:
      type: object
      description: 이슈 상세 전체 응답 모델
      properties:
        issue:
          $ref: '#/components/schemas/IssueDetailResponse'
        articles:
          type: array
          items:
            $ref: '#/components/schemas/ArticleResponse'
          description: 관련 기사 목록
      required:
        - issue
        - articles
      additionalProperties: false

    ErrorDetail:
      type: object
      description: 에러 상세 정보
      properties:
        field:
          type: string
          description: 오류 필드
          example: "perspective"
        message:
          type: string
          description: 오류 메시지
          example: "유효한 정치적 성향 값이 아닙니다."
        value:
          description: 오류 값
          example: "invalid_value"
          nullable: true
      required:
        - field
        - message
      additionalProperties: false

    ErrorResponse:
      type: object
      description: 에러 응답 모델
      properties:
        code:
          type: string
          description: 오류 코드
          example: "INVALID_PARAMETER"
        message:
          type: string
          description: 오류 메시지
          example: "유효하지 않은 파라미터가 포함되어 있습니다"
        timestamp:
          type: string
          format: date-time
          description: 오류 발생 시간
          example: "2025-06-06T12:00:00Z"
        details:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          description: 오류 상세 정보
          nullable: true
      required:
        - code
        - message
        - timestamp
      additionalProperties: false

  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    TooManyRequests:
      description: 너무 많은 요청
      headers:
        Retry-After:
          schema:
            type: integer
          description: 재시도 대기 시간(초)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: 인증 실패 - JWT 토큰이 유효하지 않거나 없음
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "AUTHENTICATION_FAILED"
            message: "유효하지 않은 JWT 토큰입니다"
            timestamp: "2025-06-06T12:00:00Z"

    Forbidden:
      description: 권한 없음 - 유효한 토큰이지만 접근 권한이 없음
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "ACCESS_DENIED"
            message: "해당 리소스에 접근할 권한이 없습니다"
            timestamp: "2025-06-06T12:00:00Z"

    ServerError:
      description: 서버 오류
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT 토큰을 사용한 인증입니다.
        Authorization 헤더에 'Bearer {token}' 형식으로 전달해주세요.
        토큰에는 사용자 이메일 정보가 포함되어 있습니다.
